Modify project
lambdaworks/scurl-detector pull request #32
Opened 2022-08-11 08:18 UTC by mvelimir

2022-08-11 09:24 UTC, drmarjanovic requested changes

2022-08-11 09:24 UTC, drmarjanovic commented on src/main/scala/io/lambdaworks/detection/Config.scala
> +  lazy val default: Config = Config(UrlDetectorOptions.Default, Set.empty, Set.empty)
Should we use `Nil` instead of `Set.empty`?

2022-08-11 09:24 UTC, drmarjanovic commented on src/main/scala/io/lambdaworks/detection/UrlDetector.scala
> +  private val allowed: Set[Url] = config.allowed.map(url => sanitize(url))
Can you use just `.map(sanitize)`?

2022-08-11 09:24 UTC, drmarjanovic commented on src/main/scala/io/lambdaworks/detection/UrlDetector.scala
> +  def checkIfValidDomain(url: Url): Boolean = {
Can this be `private`?

2022-08-11 09:24 UTC, drmarjanovic commented on src/test/scala/io/lambdaworks/detection/UrlDetectorSpec.scala
> +    val detector = UrlDetector(Config(UrlDetectorOptions.Default, Set(Url("http://lambdaworks.io/")), Set.empty))
`Set.empty` -> `Nil`?

2022-08-11 13:27 UTC, mvelimir commented on src/main/scala/io/lambdaworks/detection/Config.scala
> +  lazy val default: Config = Config(UrlDetectorOptions.Default, Set.empty, Set.empty)
There is no `Nil` for `Set` as far as I know.

2022-08-11 20:17 UTC, drmarjanovic requested changes

2022-08-11 20:17 UTC, drmarjanovic commented on src/main/scala/io/lambdaworks/detection/UrlDetector.scala
> +  private val schemeRegex: Regex = "http://|https://|ftp://".r
Is this a constant? Maybe we should rename it in that manner.

2022-08-15 08:53 UTC, drmarjanovic approved these changes

2022-08-15 08:54 UTC, merged